apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: paymentflow-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentflow-backend
  template:
    metadata:
      labels:
        app: paymentflow-backend
    spec:
      containers:
        - name: backend
          image: paymentflow-backend:local
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
